name: cleanup

on: [push]

jobs:
  push-format:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - uses: action/setup-node@v1
        with:
          node-version: 16
      - run: yarn install
      - run: yarn format
