name: deploy

on:
  push:
    tags:
      - "*"

jobs:
  heroku-deploy:
  runs-on: ubuntu-latest
  steps:
  - name: Check out repository
    uses: action/checkout@v2
    uses: action/setup-node@v1
    node-version: 16
  - run: yarn run install
  - run: yarn run build
  - name: Deploy to Heroku
    uses: akhileshns/heroku-deploy@v3.12.12
    with:
      heroku_api_key: ${{secrets.HEROKU_API_KEY}}
      heroku_app_name: "cookbook-crew-backend"
      heroku_email: "krisgumularz@gmail.com"