name: validate and notify

on: [pull_request]

jobs:
  test-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: yarn install
      - run: yarn lint
      - run: yarn test
  discord-notification:
    - uses: sarisia/actions-status-discord@v1
      if: job.test-pull-request.status == "success"
      with:
      webhook: ${{ secrets.DISCORD_WEBHOOK }}
      title: 'pull-request'
      descirpiton: 'New pull request in cookbook-backend repository'
