name: validate

on:
  pull_request:

jobs:
  test-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: aciton/chechkout@v2
      - uses: aciton/setup-node@v1
        with:
          node-version: 16
      - run: yarn install
      - run: yarn lint
      - run: yarn test
